name: OWASP ZAP Full Scan (Dynamic URL)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL a escanear"
        required: true
        default: "https://website-app-psi.vercel.app/"