name: OWASP ZAP Full Scan (Dynamic URL)

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "URL a escanear"
        required: true
        default: "https://website-app-psi.vercel.app/"

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    env:
      DEFAULT_TARGET: "https://website-app-psi.vercel.app/"

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set target URL
      run: |
        echo "TARGET_URL=${{ github.event.inputs.target_url }}" >> $GITHUB_ENV

    - name: Create ZAP directory
      run: mkdir -p zap

    - name: Run OWASP ZAP Full Scan
      run: |
        echo "Scanning: $TARGET_URL"
        docker run --rm \
        -v $(pwd)/zap:/zap/wrk \
        owasp/zap2docker-stable \
        zap-full-scan.py \
        -t $TARGET_URL \
        -r zap-report.html

    - name: Upload ZAP report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap/zap-report.html